### PR TITLE
Prevent race conditions on postgres

### PR DESCRIPTION
**Pull request by samphilipd**
Tested with 50 simultaneous connections. This 100% guarantees correctness of the sequential_id in Postgres and makes no change to the previous behavior for other database adapters.

Unfortunately this is not so trivial to implement in MySQL because table locks must be manually released.

### CODE REVIEW

**Comment by samphilipd** [comment]
Here is the test code:

```ruby
THREADS = 50
def test
  SequentialTest.destroy_all
  initial = 0

  threads = (1..THREADS).map do |i|
    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do
        SequentialTest.create!(scope_id: 42)
      end
    end
  end

  threads.each {|t| t.join}

  final = SequentialTest.pluck('max(sequential_id)')[0]

  fail('not concurrent-safe') unless final == initial + THREADS
end
```

**Comment by samphilipd** [comment]
@djreimer I enabled postgresql for your test suite and wrote a test case. It fails without the locking, and succeeds with locking enabled.

**Comment by djreimer** [comment]
Rock on! :metal: This is great. I want to run some tests on my local machine, but looks like you've covered all the bases. This should be merged soon. Thanks!

**Comment by samphilipd** [comment]
@djreimer Hey man. Let me know if there's anything you need from me or comments you have on the code that I can fix :+1:

**Comment by djreimer** [comment]
Cool will do. This is in on my todo list for a lazy post-Thanksgiving Friday

On Friday, November 27, 2015, Sam Philip <notifications@github.com> wrote:

> @djreimer <https://github.com/djreimer> Hey man. Let me know if there's
> anything you need from me or comments you have on the code that I can fix [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djreimer/sequenced/pull/16#issuecomment-160203752>.
>


-- 
Derrick

**Comment by moneytree-doug** [comment]
This was one of my concerns, and I'm glad see that it was taken care! Thanks @samphilipd !

**Pull request merged**
