### PR TITLE
Set sequential_id before validation

### PR DESCRIPTION
**Pull request by samphilipd**
- We should set before_validation not before_save so we can validate the
  presence of this field

### CODE REVIEW

**Comment by djreimer** [comment]
Thanks for the PR! We've gone down this road before, but it has unintended consequences - see #10. Since this is an auto-generated field anyway, presence validation should not be necessary. Could you explain your use case for needing a validation?

**Comment by samphilipd** [comment]
Aaah... good point. Wanted to validate presence just to make absolutely sure it will have one... but I can just as well leave this to a not-null constraint. Feel free to close this one, dude.

**Comment by djreimer** [comment]
:+1: not null constraint is a good practice, as well as a uniqueness constraint to ensure dupes don't split though (we do our best to not let that happen, but DB-level constraint is the bulletproof way).

**Comment by samphilipd** [comment]
@djreimer I haven't noticed any conditional row locking code in the source, so seems to me that it would be possible for the library to attempt to assign the same sequential ID if used concurrently.

I might put together a pull request that uses row locking to ensure this doesn't happen, what do you think about this idea?

**Comment by djreimer** [comment]
Yes, I would like to get better thread safety in this gem. I haven't had the bandwidth to come up with a robust solution, and also haven't felt the pain of this since many use cases for this gem are not high volume scenarios and thus not generally subject to race conditions in the wild. Some solutions have been floated (e.g. #13).

**Comment by samphilipd** [comment]
Hmm. I feel like advisory locking isn't the right solution for this.

The correct solution would be a database enforced exclusive write lock on the table, scoped to the same column that this gem scopes to. I'll dig into it and see if I can come up with something.

**Pull request closed without merging**
